#!/bin/bash
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V32/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V32.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V65/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V65.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V58/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V58.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V21/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V21.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V80/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V80.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V73/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V73.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V13/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V13.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V15/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V15.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V26/products?type=all&category=nvcat50001v|t1uezqf4&sort=recommend' instore_qr_ipad_V26.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V35/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V35.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V76/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V76.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V36/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V36.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V74/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V74.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V31/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V31.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V54/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V54.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V72/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V72.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V14/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V14.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V06/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V06.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V50/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V50.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V86/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V86.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V25/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V25.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V61/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V61.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V18/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V18.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V62/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V62.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V42/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V42.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V41/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V41.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V71/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V71.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V05/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V05.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V78/products?type=all&category=nvcat50001v|t1uezqf4&sort=recommend' instore_qr_ipad_V78.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V87/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V87.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V79/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V79.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V84/products?type=all&category=nvcat1920011v|t1lpuoth&sort=recommend' instore_qr_ipad_V84.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V10/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V10.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V43/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V43.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V68/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V68.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V69/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V69.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V77/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V77.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V16/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V16.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V12/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V12.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V20/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V20.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V30/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V30.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V95/products?type=all&category=nvcat50001v|t1uezqf4&sort=recommend' instore_qr_ipad_V95.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V38/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V38.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V40/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V40.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V44/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V44.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V45/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V45.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V67/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V67.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V81/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V81.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V11/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V11.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V60/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V60.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V83/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V83.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V46/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V46.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/V70/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_V70.png
python myQR.py lvlogo.png 'https://lvminicampaign.com/in-store/VC1/products?category=w-otherhandbags-wh|tfr7qdp' instore_qr_ipad_VC1.png
exit 0
